# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: sqlite-http-proxy
    main: ./cmd/sqlite-http-proxy
    binary: sqlite-http-proxy
    flags:
      - -tags=zig
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=zig cc -target x86_64-linux-musl

  - id: sqlite-http-proxy_windows
    main: ./cmd/sqlite-http-proxy
    binary: sqlite-http-proxy
    flags:
      - -tags=zig
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=zig cc -target x86_64-windows

  - id: sqlite-http-proxy_darwin
    main: ./cmd/sqlite-http-proxy
    binary: sqlite-http-proxy
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
      - CC=o64-clang

  - id: sqlite-http-refresh
    main: ./cmd/sqlite-http-refresh
    binary: sqlite-http-refresh
    flags:
      - -tags=zig
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1  
      - CC=zig cc -target x86_64-linux-musl

  - id: sqlite-http-refresh_windows
    main: ./cmd/sqlite-http-refresh
    binary: sqlite-http-refresh
    flags:
      - -tags=zig
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=zig cc -target x86_64-windows

  - id: sqlite-http-refresh_darwin
    main: ./cmd/sqlite-http-refresh
    binary: sqlite-http-refresh
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1  
      - CC=o64-clang
    
  - id: libsql-http-proxy
    main: ./cmd/libsql-http-proxy
    binary: libsql-http-proxy    
    goos:
      - linux    
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1

archives:
  - id: sqlite-http-proxy
    formats: [tar.gz]
    ids: [sqlite-http-proxy, sqlite-http-proxy_windows, sqlite-http-proxy_darwin]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{- .Binary }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - none*

  - id: sqlite-http-refresh
    formats: [tar.gz]
    ids: [sqlite-http-refresh, sqlite-http-refresh_windows, sqlite-http-refresh_darwin]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{- .Binary }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - none*

  - id: libsql-http-proxy
    formats: [tar.gz]
    ids: [libsql-http-proxy]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{- .Binary }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - none*

changelog:
  disable: true

release:  
  github:
    owner: walterwanderley
    name: sqlite-http-cache

  draft: false